{
 "title": "Cluster overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{cluster=~\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Running\",cluster=\"$cluster\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Pending|Failed|Unknown\",cluster=\"$cluster\"}[$__interval])",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\"}[$__interval]))",
     "legendFormat": "Resarts"
    }
   ]
  },
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gotk_resource_info{cluster=\"$cluster\", customresource_kind=~\"Kustomization|HelmRelease\", ready=\"True\"})  or 0",
     "legendFormat": "Running"
    },
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", customresource_kind=~\"Kustomization|HelmRelease\", ready=\"False\"}) or 0",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", customresource_kind=~\"Kustomization|HelmRelease\", suspended=\"true\"}) or 0",
     "legendFormat": "Suspended"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 7, "x": 10, "y": 1 } },
  {
   "title": "Volumes Full in Week Based on Daily Use Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    kubelet_volume_stats_available_bytes{cluster=\"$cluster\"}\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{cluster=\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n)\nor\nvector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Manifests Sources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gotk_resource_info{cluster=\"$cluster\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\", ready=\"True\"})  or 0",
     "legendFormat": "Running"
    },
    {
     "expr": "count(gotk_resource_info{cluster=\"$cluster\", customresource_kind=~\"GitRepository|HelmRepository|Bucket|OCIRepository\", ready=\"False\"}) or 0",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Node $node (CPU / Memory / Net / Disk)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "node"
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{cluster=\"$cluster\",node=\"$node\"} - node_boot_time_seconds{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Temp.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{cluster=\"$cluster\",node=\"$node\",chip=~\"platform_coretemp_0|r8169_1_1100_r8169_1_1100:00\",sensor=\"temp1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{cluster=\"$cluster\",node=\"$node\", mountpoint=\"/\"} - node_filesystem_avail_bytes{cluster=\"$cluster\",node=\"$node\", mountpoint=\"/\"}) / node_filesystem_size_bytes{cluster=\"$cluster\",node=\"$node\", mountpoint=\"/\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{cluster=\"$cluster\",node=\"$node\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{cluster=\"$cluster\",node=\"$node\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{cluster=\"$cluster\",node=\"$node\"}[$__rate_interval])",
     "legendFormat": "IO"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\",node=\"$node\"}[$__rate_interval])))",
     "legendFormat": "Real"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\",node=\"$node\"}) or 0) / sum(machine_cpu_cores{ cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\",node=\"$node\"}) or 0) / sum(machine_cpu_cores{ cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{ cluster=\"$cluster\",node=\"$node\"} - node_memory_MemAvailable_bytes{ cluster=\"$cluster\",node=\"$node\"}) / sum(node_memory_MemTotal_bytes{ cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "(sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\",node=\"$node\"}) or 0) / sum(machine_memory_bytes{ cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "(sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\",node=\"$node\"}) or 0) / sum(machine_memory_bytes{ cluster=\"$cluster\",node=\"$node\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{cluster=\"$cluster\",node=\"$node\",mode=\"idle\"}[$__interval])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",node=\"$node\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Incoming and outgoing network traffic per interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance, device) (rate(node_network_receive_bytes_total{cluster=\"$cluster\",node=\"$node\",device!~\"lo|veth.*|cni.*|flannel.*\"}[$__rate_interval]))",
     "legendFormat": "{{device}} - Rx in"
    },
    {
     "expr": "sum by (instance, device) (rate(node_network_transmit_bytes_total{cluster=\"$cluster\",node=\"$node\",device!~\"lo|veth.*|cni.*|flannel.*\"}[$__rate_interval]))",
     "legendFormat": "{{device}} - Rx out"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "description": "Percentage of filesystem space used for each mounted device",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$cluster\",node=\"$node\",fstype=~\"ext4|zfs\", mountpoint!~\"/run.*|/var/lib/docker.*|/var/lib/containerd.*|/data.*\"} - node_filesystem_avail_bytes{cluster=\"$cluster\",node=\"$node\",fstype=~\"ext4|zfs\", mountpoint!~\"/run.*|/var/lib/docker.*|/var/lib/containerd.*|/data.*\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{cluster=\"$node\",fstype=~\"ext4|zfs\", mountpoint!~\"/run.*|/var/lib/docker.*|/var/lib/containerd.*|/data.*\"}",
     "legendFormat": "Max {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "Average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{cluster=\"$cluster\",node=\"$node\"}[$__rate_interval]) / irate(node_disk_reads_completed_total{cluster=\"$cluster\",node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{cluster=\"$cluster\",node=\"$node\"}[$__rate_interval]) / irate(node_disk_writes_completed_total{cluster=\"$cluster\",node=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "PVC Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{cluster=\"$cluster\"}"
    },
    {
     "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info{cluster=\"$cluster\"} ) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=\"$cluster\"} )) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info{cluster=\"$cluster\"} ) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=\"$cluster\"} )))"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"} )"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{cluster=\"$cluster\"} )"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"} ))"
    }
   ]
  },
  {
   "title": "Daily Volume Use Rate",
   "type": "timeseries",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kubelet_volume_stats_used_bytes{cluster=\"$cluster\",node=~\"$node\"} [1d])",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Traefik",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Code ",
     "type": "piechart",
     "description": "Mean Distribution",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{protocol=\"http\",cluster=\"$cluster\"}[$__interval])) by (method, code)",
       "legendFormat": "{{method}}[{{code}}]"
      }
     ]
    },
    {
     "title": "Top slow services",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(15,\n    label_replace(\n        traefik_service_request_duration_seconds_sum{protocol=\"http\",cluster=\"$cluster\"} / \n          traefik_service_request_duration_seconds_count{protocol=\"http\",cluster=\"$cluster\"},\n        \"service\", \"$1\", \"service\", \"([^@]+)@.*\")\n)\n\n",
       "legendFormat": "{{method}}[{{code}}] on {{service}}"
      }
     ]
    }
   ]
  }
 ]
}