apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ovh-credentials
spec:
  secretStoreRef:
    name: openbao-eso
    kind: ClusterSecretStore
  refreshInterval: 24h
  dataFrom:
    - extract:
        key: salamandre/ovh
