---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
spec:
  releaseName: vm-stack
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.90.2"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
      interval: 12h
  install:
    createNamespace: true
    crds: Skip
  upgrade:
    crds: Skip
  values:
    kubelet:
      vmScrape:
        spec:
          interval: "30s"
          metricRelabelConfigs:
            # Drop of highest cardinality and useless labels (churn)
            - action: labeldrop
              regex: (uid|id|metrics_path|replicaset|endpoint_slice)
            # Drop of control plane buckets (apiserver, etcd, etc)
            - action: drop
              source_labels: [__name__]
              regex: (apiserver_request_duration_seconds_bucket|etcd_request_duration_seconds_bucket|apiserver_request_body_size_bytes_bucket|apiserver_watch_list_duration_seconds_bucket|apiserver_watch_cache_read_wait_seconds_bucket|apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket|workqueue_queue_duration_seconds_bucket|workqueue_work_duration_seconds_bucket|scheduler_plugin_execution_duration_seconds_bucket|grafana_http_response_size_bytes_bucket)
            # Drop of cAdvisor noise (kubelet)
            - action: drop
              source_labels: [__name__]
              regex: (container_tasks_state|container_memory_failures_total|container_memory_mapped_file|container_network_tcp_usage_total|container_network_udp_usage_total|container_blkio_.*)

    prometheus-node-exporter:
      fullnameOverride: node-exporter
      resources:
        requests:
          cpu: 20m
          memory: 25Mi
        limits:
          cpu: 30m
          memory: 50Mi

      vmScrape:
        spec:
          interval: "30s"
          metricRelabelConfigs:
            - action: labeldrop
              regex: (uid|id|beta_kubernetes_io_.*|kubernetes_io_arch|kubernetes_io_os|node_kubernetes_io_instance_type|node_role_kubernetes_io_.*|metrics_path)

    kube-state-metrics:
      fullnameOverride: kube-state-metrics
      resources:
        requests:
          cpu: 4m
          memory: 60Mi
        limits:
          cpu: 100m
          memory: 120Mi

      vmScrape:
        spec:
          interval: "30s"
          metricRelabelConfigs:
            - action: labeldrop
              regex: (uid|id|beta_kubernetes_io_.*|kubernetes_io_arch|kubernetes_io_os|node_kubernetes_io_instance_type|node_role_kubernetes_io_.*)
            - action: drop
              source_labels: [__name__]
              regex: (kube_secret_.*|kube_configmap_.*|kube_endpoint.*|kube_lease_.*|kube_.+_created|kube_.+_metadata_resource_version|kube_pod_init_container_.*)

    victoria-metrics-operator:
      fullnameOverride: victoria-metrics-operator

      operator:
        enable_converter_ownership: true

      # Disable CRDs
      crds:
        enabled: false
        plain: false
        cleanup:
          enabled: false

    # Global resources
    vmagent:
      spec:
        resources:
          requests:
            cpu: 90m
            memory: 275Mi
          limits:
            memory: 320Mi

    # Disable unneeded alert rules
    defaultRules:
      groups:
        etcd:
          create: false
        vmcluster:
          create: false

    ## In k3s alls bellow components is combined in "kubelet"
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeApiServer:
      enabled: false
    kubeEtcd:
      enabled: false

    # Disable default grafana dashboards
    defaultDashboards:
      enabled: false
    ## Disable embedded grafana for deploy own
    grafana:
      enabled: false
    # Disable CRDs
    prometheus-operator-crds:
      enabled: false

    fullnameOverride: vm-stack
