#!/usr/bin/env bash
#MISE description="Generate admin credentials"
#USAGE arg "<environment>" env="ENVIRONMENT" help="Targeted environment" {
#USAGE   choices "dev" "production"
#USAGE }

set -euo pipefail
# shellcheck disable=SC1091
source "$(dirname "$0")/../_lib.sh"

# Validate and parse arguments
ENVIRONMENT=${usage_environment?}
CREDS_FOLDER="${OUT_DIR?}/credentials/${ENVIRONMENT}"

check_command pwgen
check_command openssl

DEFAULT_LENGTH=32
randpw () {
  pwgen -cnysB -r "'\"\`{}\\|" "${1:-$DEFAULT_LENGTH}" 1
}

insert_value() {
  # Create file if not exist because from v4 yq don't create it
  [[ -f $1 ]] || touch $1
  if [[ "$(yq "$2" "$1")" = "null" ]]; then
    yq -i "$2 = \"$3\"" "$1"
  fi
}

mkdir -p "$CREDS_FOLDER"

##
# Admin passwords
##
FILE="$CREDS_FOLDER/admin_passwords.yaml"
# Salamandre credentials
insert_value "$FILE" .salamandre.zitadel "$(randpw 16)"
insert_value "$FILE" .salamandre.nextcloud "$(randpw 16)"
insert_value "$FILE" .salamandre.forgejo "$(randpw 16)"

if [[ "$(yq .salamandre.vaultwarden "$FILE")" = "null" ]]; then
  token=$(openssl rand -base64 48)
  insert_value "$FILE" .salamandre.vaultwarden.value "$token"
  insert_value "$FILE" .salamandre.vaultwarden.salt "$(openssl rand -base64 32)"
  unset "$token"
fi

# Baku credentials
insert_value "$FILE" .baku.seaweedfs "$(randpw 16)"
insert_value "$FILE" .baku.grafana "$(randpw 16)"

##
# Zitadel masterkey
##
FILE="$CREDS_FOLDER/zitadel_masterkey"
if [ ! -e "$FILE" ]; then
  touch "$FILE"
  pwgen -cn 32 1 > "$FILE"
fi

##
# Forgejo runner token
##
FILE="$CREDS_FOLDER/forgejo_runner_token"
if [ ! -e "$FILE" ]; then
  touch "$FILE"
  openssl rand -hex 20 > "$FILE"
fi

##
# Discord webhook url
##
FILE="$CREDS_FOLDER/discord_webhook_url.yaml"
if [ ! -e "$FILE" ]; then
  echo "Enter discord webhook url:"
  IFS= read -r webhookUrl
  insert_value "$FILE" .alerts "$webhookUrl"

  echo "Enter discord webhook url for Watchdog:"
  IFS= read -r webhookUrl
  insert_value "$FILE" .watchdog "$webhookUrl"
fi
