#!/usr/bin/env bash
#MISE description="Retrieve an admin credentials"
#USAGE arg "<environment>" env="ENVIRONMENT" help="Targeted environment" {
#USAGE   choices "dev" "production"
#USAGE }
#USAGE arg "<application>" help="Wanted application" {
#USAGE   choices "openbao" "zitadel" "nextcloud" "forgejo" "vaultwarden" "seaweedfs" "grafana"
#USAGE }

set -euo pipefail
# shellcheck disable=SC1091
source "$(dirname "$0")/../_lib.sh"

# Validate and parse arguments
ENVIRONMENT=${usage_environment?}
APPLICATION=${usage_application?}
CREDS_FOLDER="${OUT_DIR?}/credentials/${ENVIRONMENT}"

check_file() {
  if [[ ! -f "$1" ]]; then
    echo "Missing file $1"
    exit 1
  fi
}

# Ensure file exist
FILE="$CREDS_FOLDER/admin_passwords.yaml"
check_file "$FILE"

# Retrieve domain
DOMAIN="$(yq ._domain "$FILE")"
if [[ -z "$DOMAIN" || "$DOMAIN" = "null" ]]; then
  DOMAIN="DOMAIN.TLD"
fi

case "$APPLICATION" in
  openbao)
    FILE="$CREDS_FOLDER/openbao.json"
    check_file "$FILE"
    echo "Url: https://secrets.$DOMAIN/ui/vault/auth?with=token"
    echo "Root token: $(jq -r .root_token "$FILE")"
  ;;
  zitadel)
    echo "Url: https://sso.$DOMAIN/ui/v2/login/loginname"
    echo "Username: admin"
    echo "Password: $(yq .salamandre.zitadel "$FILE")"
  ;;
  nextcloud)
    echo "Url: https://cloud.$DOMAIN/login?direct=1"
    echo "Username: admin"
    echo "Password: $(yq .salamandre.nextcloud "$FILE")"
  ;;
  forgejo)
    echo "Url: https://git.$DOMAIN/user/login"
    echo "Username: root"
    echo "Password: $(yq .salamandre.forgejo "$FILE")"
  ;;
  vaultwarden)
    echo "Url: https://vault.$DOMAIN/admin"
    echo "Token: $(yq .salamandre.vaultwarden.value "$FILE")"
  ;;
  seaweedfs)
    echo "Url: https://baku.$DOMAIN/login"
    echo "Username: admin"
    echo "Password: $(yq .baku.seaweedfs "$FILE")"
  ;;
  grafana)
    echo "Url: https://monitor.$DOMAIN/login"
    echo "Username: admin"
    echo "Password: $(yq .baku.grafana "$FILE")"
  ;;
esac
