apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone-config
spec:
  secretStoreRef:
    name: openbao-eso
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    template:
      type: Opaque
      data:
        rclone.conf: |
          [s3]
          type = s3
          provider = Other
          endpoint = {{ .endpoint }}
          access_key_id = {{ .accessKey }}
          secret_access_key = {{ .secretKey }}
          upload_cutoff = 50Mi
          chunk_size = 50Mi
          force_path_style = true
          no_check_bucket = true

  dataFrom:
    - extract:
        key: salamandre/data/backup/s3
---
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
type: Opaque
stringData:
  url: ${ALERTS_DISCORD_WEBHOOK_URL}
