---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name zfs-localpv
spec:
  releaseName: *name
  interval: 1h
  chart:
    spec:
      chart: zfs-localpv
      version: "2.10.1"
      sourceRef:
        kind: HelmRepository
        name: openebs-zfslocalpv
  values:
    zfsNode:
      resources:
        requests:
          cpu: 10m
          memory: 129Mi
        limits:
          memory: 256Mi # Don't follow KRR recommendation due to an issue with constantly increase of memory (report to openebs?)
    zfsController:
      resources:
        requests:
          cpu: 10m
          memory: 49Mi
        limits:
          memory: 49Mi
    crds:
      zfsLocalPv:
        enabled: true
      csi:
        volumeSnapshots:
          enabled: false
