#!/usr/bin/env bash
#MISE description="Create virtual machines"
#MISE depends=["init"]
#MISE interactive=true
#USAGE flag "--host <host>" help="Limit to only specified machine" {
#USAGE   choices "salamandre" "baku" "all"
#USAGE   default "all"
#USAGE }

set -euo pipefail
# shellcheck disable=SC1091
source "$(dirname "$0")/../_lib.sh"

# Start libvirt
echo "Ensure libvirt is running"
systemctl is-active --quiet libvirtd || sudo systemctl start libvirtd
systemctl is-active --quiet virtlogd || sudo systemctl start virtlogd

# Create root CA if not exist
if [ ! -f "${OUT_DIR?}/vms/rootCA.pem" ]; then
  echo "Creating CA certificates"
  CAROOT="${OUT_DIR?}/vms" mkcert -install
fi

# Reference SSH key
if [ ! -f "${OUT_DIR?}/vms/ssh_key_path" ]; then
  echo "Enter the public ssh key file you want use [~/.ssh/id_ed25519.pub]:"
  IFS= read -r key_path
  key_path=${key_path:-~/.ssh/id_ed25519.pub}
  key_path=$(realpath -s "${key_path/#\~/$HOME}") # Resolve relative path

  if [ ! -f "$key_path" ]; then
    echo "File \"$key_path\" doesn't exist"
    exit 1
  else
    echo "$key_path" > "${OUT_DIR?}/vms/ssh_key_path"
  fi
fi

echo "Running ansible"
run_ansible vms_create dev "--ask-become-pass $(limit_flag "${usage_host:-}")"
