{
 "title": "Volumes / Cluster",
 "description": "Dashboard of Kubernetes / OpenShift volume information at cluster level as exported by Prometheus connected to Kubernetes / OpenShift.",
 "tags": [
  "openshift",
  "k8s",
  "storage"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_OPENSHIFT_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubelet_node_name,cluster)"
    }
   },
   {
    "name": "pvc_percent_used_warning_threshold",
    "label": "PVC % Used Warning Threshold",
    "query": "80"
   }
  ]
 },
 "panels": [
  { "title": "Current Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  {
   "title": "User Namespace Volumes Full in Week Based on Daily Use Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (\n      (kubelet_volume_stats_available_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"})\n    )\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)",
     "legendFormat": "alerts"
    }
   ]
  },
  { "title": "Dashboard Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 } },
  {
   "title": "Running PVCs Above % Used Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) >= ($pvc_percent_used_warning_threshold / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "Unbound PVCs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max (sum by (exported_namespace) (pv_collector_unbound_pvc_count{cluster=~\"$cluster\"}))) or (vector(0))"
    }
   ]
  },
  {
   "title": "Alert Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table",
     "gridPos": { "h": 14, "w": 7, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(\n  (\n    (kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"} ) \n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"}[1w], 7 * 24 * 60 * 60) < 0)\n  )\n)"
      }
     ]
    },
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(\n  (\n    ((kubelet_volume_stats_used_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"} ) * 0) + 1\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Infrastructure Namespace Volumes Full in Week Based on Daily Use Rate - Predicted Available Space History",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\n  (predict_linear(kubelet_volume_stats_available_bytes {namespace=~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "User Namespace Volumes Full in Week Based on Daily Use Rate - Current",
     "type": "table",
     "gridPos": { "h": 13, "w": 7, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(\n  (\n    (\n      (kubelet_volume_stats_used_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"})\n    )\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)"
      }
     ]
    },
    {
     "title": "User Namespace Volumes Full in Week Based on Daily Use Rate - Alert History",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(\n  (\n    (\n      (\n        (kubelet_volume_stats_used_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"})\n      )\n      * 0 + 1\n    )\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "User Namespace Volumes Full in Week Based on Daily Use Rate - Predicted Available Space History",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\n  (predict_linear(kubelet_volume_stats_available_bytes {namespace!~\"(openshift-.*|kube-.*|default|logging)\",cluster=~\"$cluster\"}[1d], 7 * 24 * 60 * 60) < 0)\n)",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold Stats - Current",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(kube_persistentvolumeclaim_info{cluster=~\"$cluster\"}) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"})) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"} )) and ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) >= ($pvc_percent_used_warning_threshold / 100))"
      },
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) >= ($pvc_percent_used_warning_threshold / 100)"
      }
     ]
    },
    {
     "title": "Running PVCs Above % Used Warning Threshold - History",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 17, "x": 7, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(\n  ((max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) * 0 +1)\n  and\n  (\n    (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} ))\n  ) >= ($pvc_percent_used_warning_threshold / 100)\n)"
      }
     ]
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bound PVCs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (pv_collector_bound_pvc_count{cluster=~\"$cluster\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "PVC Stats",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{cluster=~\"$cluster\"}"
    },
    {
     "expr": "(1-max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info{cluster=~\"$cluster\"} ) ) unless (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) or ((max by (persistentvolumeclaim, namespace) (kube_persistentvolumeclaim_info{cluster=~\"$cluster\"} ) ) and (max by (namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )))"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"})"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )"
    },
    {
     "expr": "max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"} )"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} ))"
    }
   ]
  },
  {
   "title": "Use",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Running PVCs Used Bytes",
     "type": "timeseries",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} ))",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Running PVCs % Used",
     "type": "timeseries",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster\"} )) * 100",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Use Rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hourly Volume Use Rate",
     "type": "timeseries",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} [1h])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Daily Volume Use Rate",
     "type": "timeseries",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} [1d])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    },
    {
     "title": "Weekly Volume Use Rate",
     "type": "timeseries",
     "description": "WARNING: Any PVCs that are not bound to a running pod will not show up in this state.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"} [1w])",
       "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
      }
     ]
    }
   ]
  }
 ]
}