# vscode-kubernetes-tools: exclude
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallabag
resources:
  - dnsendpoint.yaml
  - secret.yaml
  - helm-repository.yaml
  - helm-release.yaml
configMapGenerator:
  - name: wallabag-nginx
    files:
      - configs/nginx.conf
generatorOptions:
  disableNameSuffixHash: true
