apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
spec:
  values:
    allInOne:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          memory: 1Gi

      data:
        size: 10Gi
