apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs
spec:
  values:
    allInOne:
      resources: # Don't follow KRR recommendation to handle increasing files number
        requests:
          cpu: 10m
          memory: 256Mi
        limits:
          memory: 512Mi

      data:
        size: 10Gi
