{
 "title": "MinIO Cluster",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(minio_software_version_info, cluster)"
    }
   },
   {
    "name": "scrape_jobs",
    "query": {
     "query": "label_values(minio_software_version_info{cluster=~\"$cluster\"}, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{cluster=~\"$cluster\",job=\"$scrape_jobs\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Inbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (minio_s3_traffic_received_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(minio_bucket_usage_total_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}) by (job)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minio_bucket_objects_version_distribution{cluster=~\"$cluster\",job=\"$scrape_jobs\"}) by (range)",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Total Open FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (minio_node_file_descriptor_open_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total S3 Traffic Outbound",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (minio_s3_traffic_sent_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Goroutines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum without (server,instance) (minio_node_go_routine_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_online_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Online Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_disk_online_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minio_bucket_usage_total_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "S3 API Data Received Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(minio_s3_traffic_received_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{cluster}}]"
    }
   ]
  },
  {
   "title": "S3 API Data Sent Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(minio_s3_traffic_sent_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Total Offline Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_nodes_offline_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Offline Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_disk_offline_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minio_bucket_usage_object_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}) by (job)"
    }
   ]
  },
  {
   "title": "Time Since Last Scan Activity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minio_usage_last_activity_nano_seconds{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,api) (increase(minio_s3_requests_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{api}} [{{cluster}}]"
    }
   ]
  },
  {
   "title": "S3 API Request 4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,api) (increase(minio_s3_requests_4xx_errors_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{api}} [{{cluster}}]"
    }
   ]
  },
  {
   "title": "S3 API Request 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster,api) (increase(minio_s3_requests_5xx_errors_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{api}} [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "CPU Usage Rate [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "Memory Used [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Drive Used Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_disk_used_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "Used Capacity [{{cluster}}:{{disk}}]"
    }
   ]
  },
  {
   "title": "Drives Free Inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_disk_free_inodes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "Free Inodes [{{cluster}}:{{disk}}]"
    }
   ]
  },
  {
   "title": "Node Syscalls",
   "type": "timeseries",
   "description": "Number of online disks per MinIO Server",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{cluster}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Node File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{cluster=~\"$cluster\",job=\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{cluster}}]"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{cluster}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{cluster=~\"$cluster\",job=\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{cluster}}]"
    }
   ]
  }
 ]
}