# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name seaweedfs
  annotations:
    host: &host baku.${DOMAIN_NAME}
spec:
  releaseName: *name
  interval: 1h
  chart:
    spec:
      chart: seaweedfs
      version: "4.46.0"
      sourceRef:
        kind: HelmRepository
        name: seaweedfs
  install:
    createNamespace: true
  values:
    global:
      seaweedfs:
        enableSecurity: false
        masterServer: seaweedfs-all-in-one.seaweedfs.svc.cluster.local.:9333
        monitoring:
          enabled: true

    s3:
      enabled: false # Enabled by allInOne.s3.enabled
      ingress:
        enabled: true
        className: traefik
        host: *host
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: s3
        tls:
          - hosts:
              - *host

    admin:
      enabled: true
      extraArgs: # Workaround until V4.46.1 (https://github.com/seaweedfs/seaweedfs/issues/11234)
        - "-ip=0.0.0.0"

      secret:
        existingSecret: seaweedfs-admin-credentials
        userKey: adminUser
        pwKey: adminPassword

      resources:
        requests:
          cpu: 5m
          memory: 69Mi
        limits:
          memory: 69Mi

      data:
        type: "persistentVolumeClaim"
        storageClass: openebs-zfspv
        size: 1Gi

      ingress:
        enabled: true
        className: traefik
        host: *host
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        tls:
          - hosts:
              - *host

    allInOne:
      enabled: true
      replicas: 1 # Number of replicas (note: multiple replicas may require shared storage)

      s3:
        enabled: true

        domainName: *host
        enableAuth: true
        existingConfigSecret: seaweedfs-s3-config

        createBuckets:
          - name: backup-salamandre-pg
            anonymousRead: false
          - name: backup-salamandre-pvc
            anonymousRead: false
            # ttl: 1y

      resources: # Don't follow KRR recommendation to handle increasing files number
        requests:
          cpu: 10m
          memory: 1024Mi
        limits:
          # cpu: 2 # This is default value from chart
          memory: 2048Mi

      data:
        type: persistentVolumeClaim
        storageClass: openebs-zfspv
        size: 500Gi

    # Disable unused parts
    master:
      enabled: false
    volume:
      enabled: false
    filer:
      enabled: false
