apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-s3-config
spec:
  secretStoreRef:
    name: openbao-eso
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    template:
      type: Opaque
      data:
        seaweedfs_s3_config: |
          {
            "identities": [
              {
                "name": "admin",
                "credentials": [
                  {
                    "accessKey": "{{ .adminUser }}",
                    "secretKey": "{{ .adminPassword }}"
                  }
                ],
                "actions": ["Admin", "Read", "Write", "List", "Tagging"]
              },
              {
                "name": "salamandre-backup",
                "credentials": [
                  {
                    "accessKey": "{{ .accessKey }}",
                    "secretKey": "{{ .secretKey }}"
                  }
                ],
                "actions": [
                  "Read:backup-salamandre-pg", "Write:backup-salamandre-pg", "List:backup-salamandre-pg", "Tagging:backup-salamandre-pg",
                  "Read:backup-salamandre-pvc", "Write:backup-salamandre-pvc", "List:backup-salamandre-pvc", "Tagging:backup-salamandre-pvc"
                ]
              }
            ]
          }
  dataFrom:
    - extract:
        key: baku/seaweedfs/auth
        # Expected keys: adminUser, adminPassword
    - extract:
        key: salamandre/data/backup/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs-admin-credentials
spec:
  secretStoreRef:
    name: openbao-eso
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    template:
      type: Opaque
      metadata:
        labels:
          reloader/watch: enabled
      data:
        adminUser: '{{ .adminUser }}'
        adminPassword: '{{ .adminPassword }}'
  dataFrom:
    - extract:
        key: baku/seaweedfs/auth
